#!/usr/bin/env python3
"""
Pre-process _content.yml to generate legacy YAML files (_notebooks.yaml, _menu.yml, _config.yml, etc.)
Outputs files in the project root, overwriting existing ones.
"""
import yaml
import sys
from pathlib import Path

# --- Paths ---
repo_root = Path(__file__).parent.parent.resolve()
content_yml = repo_root / '_content.yml'

# --- Output files ---
# Place autogenerated files in .autogen directory at project root
autogen_dir = repo_root / '.autogen'
autogen_dir.mkdir(parents=True, exist_ok=True)
out_files = {
    'notebooks': autogen_dir / '_notebooks.yaml',
    'menu': autogen_dir / '_menu.yml',
    'config': autogen_dir / '_config.yml',
}

def main():
    if not content_yml.exists():
        print(f"[ERROR] {content_yml} not found.")
        sys.exit(1)
    with open(content_yml, 'r') as f:
        content = yaml.safe_load(f)
    # --- Generate _notebooks.yaml ---
    notebooks = []
    # Collect all chapter notebook files
    if 'chapters' in content:
        for chapter in content['chapters']:
            if isinstance(chapter, dict) and 'files' in chapter:
                for f in chapter['files']:
                    if 'file' in f:
                        notebooks.append(f['file'])
    # Add homeworks if present
    if 'homework' in content:
        for hw in content['homework']:
            if 'file' in hw:
                notebooks.append(hw['file'])
    # Add activities if present (if you want them in the build)
    if 'activities' in content:
        for act in content['activities']:
            if 'file' in act:
                notebooks.append(act['file'])
    # Remove duplicates while preserving order
    seen = set()
    notebooks_unique = []
    for nb in notebooks:
        if nb not in seen:
            notebooks_unique.append(nb)
            seen.add(nb)
    # Indent list for YAML output
    import io
    notebooks_comment = """# AUTO-GENERATED FILE. DO NOT EDIT.\n# This file was generated from _content.yml by scripts/preprocess_content_yml.py\n# Edit _content.yml instead and re-run the preprocessor.\n"""
    buf = io.StringIO()
    buf.write(notebooks_comment)
    buf.write('notebooks:\n')
    for nb in notebooks_unique:
        buf.write(f'  - {nb}\n')
    with open(out_files['notebooks'], 'w') as f:
        f.write(buf.getvalue())
    print(f"[OK] Wrote {out_files['notebooks']}")

    # --- Generate _menu.yml ---
    # Build menu structure from _content.yml (navigation, chapters, activities, resources, about)
    menu = []
    # Home
    menu.append({'title': 'Home', 'path': 'index.html'})
    # Chapters
    chapters_menu = {'title': 'Chapters', 'path': 'chapters.html', 'children': []}
    if 'chapters' in content:
        for chapter in content['chapters']:
            if 'files' in chapter:
                for f in chapter['files']:
                    title = f.get('title') or f.get('file')
                    path = Path(f.get('file', '')).with_suffix('.html').name if 'file' in f else ''
                    if title and path:
                        chapters_menu['children'].append({'title': title, 'path': path})
    menu.append(chapters_menu)
    # Activities/Homework
    activities_menu = {'title': 'Activities', 'path': 'activities.html', 'children': []}
    if 'homework' in content:
        for hw in content['homework']:
            title = hw.get('title') or hw.get('file')
            path = Path(hw.get('file', '')).with_suffix('.html').name if 'file' in hw else ''
            if title and path:
                activities_menu['children'].append({'title': title, 'path': path})
    menu.append(activities_menu)
    # Resources
    menu.append({'title': 'Resources', 'path': 'resources.html'})
    # About
    menu.append({'title': 'About', 'path': 'about.html'})
    menu_comment = """# AUTO-GENERATED FILE. DO NOT EDIT.\n# This file was generated from _content.yml by scripts/preprocess_content_yml.py\n# Edit _content.yml instead and re-run the preprocessor.\n"""
    buf = io.StringIO()
    buf.write(menu_comment)
    yaml.dump({'menu': menu}, buf, sort_keys=False, allow_unicode=True)
    with open(out_files['menu'], 'w') as f:
        f.write(buf.getvalue())
    print(f"[OK] Wrote {out_files['menu']}")

    # --- Generate _config.yml ---
    config = content.get('config', {})
    config_comment = (
        """# AUTO-GENERATED FILE. DO NOT EDIT.\n# This file was generated from _content.yml by scripts/preprocess_content_yml.py\n# Edit _content.yml instead and re-run the preprocessor.\n"""
    )
    with open(out_files['config'], 'w') as f:
        f.write(config_comment)
        yaml.dump(config, f, sort_keys=False, allow_unicode=True)
    print(f"[OK] Wrote {out_files['config']}")
if __name__ == '__main__':
    main()
